# Site settings
title: Sathish Jayaraman - Full Stack Developer | Software Engineer
email: sathishj.official@gmail.com
description: My name is Sathish Jayaraman also known as scriperdj. I am a full-stack Engineer. This is my portfolio & blogging website. I write about technology, travel and anything I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sathish.me" # the base hostname & protocol for your site
twitter_username: scriperdj
github_username:  scriperdj
gems: [jekyll-paginate, pygments.rb]
paginate: 6
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
highlighter: pygments
